// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txknurlgrmlxdivjiolx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4a251cmxncm1seGRpdmppb2x4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDUxMzMsImV4cCI6MjA2NTk4MTEzM30.zz4gZBKdZoL17pRvwUcYxSUcVCvrOITNedhzG5E9yTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);